#!/usr/bin/env bash
# Pin the semantic autonomous router across its prompt, validator, harness docs,
# SDK examples, and machine-readable output.
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/fixed-string-coverage.sh"

checks=(
  "skills/auto/SKILL.md	lib/task-route.sh"
  "skills/auto/SKILL.md	Skill(loop-spec:micro)"
  "skills/auto/SKILL.md	Skill(loop-spec:debug)"
  "skills/auto/SKILL.md	Skill(loop-spec:cycle)"
  "skills/auto/SKILL.md	AUTONOMOUS_ROUTE"
  "skills/auto/SKILL.md	merge-conflict resolution"
  "skills/auto/SKILL.md	profile:{profile}"
  "skills/auto/SKILL.md	\"destructive\": false"
  "skills/auto/SKILL.md	**only** when"
  "skills/micro/SKILL.md	model: inherit"
  "lib/task-route.sh	invalid-classification"
  "lib/task-route.sh	micro-requires-low-ambiguity"
  "lib/task-route.sh	debug-task-kind-mismatch"
  "lib/task-route.sh	workingTreeConflict"
  "lib/task-route.sh	--classification"
  "lib/cycle-driver.sh	cycle-profile select"
  "lib/cycle-driver.sh	Execution profile: resolved once"
  "skills/micro/SKILL.md	autonomous runs (inline"
  "skills/micro/SKILL.md	brief so intake"
  "skills/debug/SKILL.md	with the path, hand off"
  "hooks/team/grill-inject.sh	/loop-spec:auto"
  "hooks/team/micro-inject.sh	/loop-spec:auto"
  "skills/shared/autonomous-mode.md	/loop-spec:auto"
  "skills/shared/autonomous-mode.md	loop-spec-auto"
  "skills/shared/autonomous-mode.md	Destructive work is never compact."
  "skills/shared/autonomous-mode.md	compact-profile.md"
  "skills/shared/compact-profile.md	gatePlan"
  "skills/shared/compact-profile.md	tamperScan"
  "skills/shared/compact-profile.md	Exact-SHA"
  "skills/shared/adk-harness.md	adk run"
  "skills/shared/adk-harness.md	compact-profile.md"
  "skills/shared/opencode-harness.md	loop-spec-auto"
  "skills/shared/opencode-harness.md	compact-profile.md"
  "skills/shared/codex-harness.md	compact-profile.md"
  "README.md	/loop-spec:auto"
  "README.md	AUTONOMOUS_ROUTE"
  "README.md	compact profile"
  "docs/loop-spec/configuration.md	compact-profile.md"
  "skills/shared/adk-harness.md	route-terminal-guard.sh"
  "skills/shared/opencode-harness.md	route-terminal-guard.sh"
)

check_fixed_strings "${checks[@]}"

finish_fixed_string_coverage
