#!/usr/bin/env bash
# Pins the contract lines the 2026-09-07 live headless cycle on tf-meldn showed were
# missing (the 2026-09-07 tf-meldn runs): subagents get absolute template
# paths, task sections are rendered from tasks.json, state changes name their command,
# the headless join is stated as fact, and the tool-boundary backstops are wired.
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/fixed-string-coverage.sh"

checks=(
  $'skills/discuss/SKILL.md\tartifact-templates/PATTERNS.md.template'
  $'skills/discuss/SKILL.md\tlib/feature-write.sh" set "$feature_dir" artifacts.patternsPrefetch'
  $'skills/plan/SKILL.md\tartifact-templates/PATTERNS.md.template'
  $'skills/plan/SKILL.md\tartifact-templates/PLAN.md.template'
  $'agents/planner.md\ttemplate_path'
  $'agents/pattern-mapper.md\tnever search the disk'
  $'skills/shared/dispatch.md\tThis holds'
  $'skills/shared/dispatch.md\tunder `claude -p`'
  $'skills/shared/critique-gate-protocol.md\tunder `claude -p` as well'
  $'skills/shared/critique-gate-protocol.md\tACCEPTED as `[minor]`'
  $'hooks/team/result-forgery-guard.sh\tbash lib/feature-write.sh set <feature_dir> <dot.path>'
  $'hooks/hooks.json\thooks/team/artifact-lint-feedback.sh'
  $'hooks/hooks.json\thooks/team/dispatch-prompt-guard.sh'
  $'hooks/team/artifact-lint-feedback.sh\tbefore reporting DONE'
  $'lib/execute-step.sh\tdispatchable:false, reason:"blocked"'
  $'skills/cycle/SKILL.md\tDo not check its path with `ls`'
  $'lib/acceptance-lint.sh\t=~ [^[:space:]]'
  $'lib/evidence.sh\trefusing an email address or credential path'
  $'lib/owned-gitignore.sh\tensure <repo> <line>...'
  $'lib/execute-prepare.sh\tdispatch/environment.txt'
  $'lib/dispatch-files.sh\tdispatch/tasks-collapsed.json'
  $'lib/dispatch-files.sh\tDo not read SPEC.md, PLAN.md, PATTERNS.md, or EVIDENCE.md'
  $'lib/execute-step.sh\t(.memberIds // [.id])[]'
  $'lib/execute-step.sh\tverifyCommand:$vc'
  $'skills/shared/execute-subagent.md\tDo NOT run the task\'s verify command'
  $'skills/shared/execute-subagent.md\tDo not open SPEC.md, PLAN.md'
  $'agents/planner.md\tlib/task-batch.sh'
  $'docs/loop-spec/configuration.md\tLOOP_SPEC_TASK_BATCH_AUTO'
  $'lib/iterate-judged.sh\troute=escalate'
  $'lib/graph/driver.py\toperator action needed'
  $'agents/iterate-judge.md\tneeds_operator'
  $'skills/iterate/SKILL.md\t`escalate`: the gap needs an operator'
  $'lib/converged-floor.sh\tmark it BLOCKED'
  $'skills/shared/artifact-templates/VERIFICATION.md.template\tBLOCKED'
  $'agents/verifier.md\tPASS/FAIL/BLOCKED/N/A'
  $'skills/shared/execute-subagent.md\tYour final message IS the verdict'
  $'skills/shared/execute-subagent.md\tpass it according to the harness\'s model contract'
  $'skills/cycle/SKILL.md\tDo not call `init` again'
  $'skills/shared/critique-gate-protocol.md\tthe lead does not inline it'
  $'skills/plan/SKILL.md\tplan-conflicts.sh" edges'
  $'skills/shared/review-prompts/prose-pruning.md\tprose-lines'
  $'skills/shared/team-prompts/critic.md\tRead only the cited `EVID-NNN` rows'
  $'lib/graph/driver.py\theadless invocation; working in place'
  $'lib/checkpoint-pr.sh\tBlocked verification'
  $'lib/plan-conflicts.sh\tprints the updated array on stdout'
  $'lib/execute-rung.sh\tthe harness task list is disabled under claude -p'
  $'lib/integrate-task.sh\tis_tool_cache_path'
  $'hooks/team/artifact-lint-feedback.sh\tverification-grounding-lint.sh'
  $'lib/verify-gate.sh\t@path'
  $'skills/verify/SKILL.md\t--minors @'
  $'skills/cycle/SKILL.md\t--completed <N>'
  $'skills/shared/execute-subagent.md\tno `name` key'
  $'lib/graph/driver.py\tdatetime.timezone.utc'
  $'lib/graph/driver.py\tThe gate runs on every return'
  $'lib/graph/driver.py\tLOOP_SPEC_SAME_SESSION must be 0 or 1'
)

check_fixed_strings "${checks[@]}"
finish_fixed_string_coverage
