#!/usr/bin/env bash
# Tests for lib/codex-install.sh — install into a temp Codex home and assert
# skills, custom agents, env, and hooks land on the documented discovery
# surfaces; manifest-driven uninstall removes exactly its own.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
LIB="$REPO/lib/codex-install.sh"
PASS=0
FAIL=0

check() {
  local name="$1" expected="$2" actual="$3"
  if [[ "$actual" == "$expected" ]]; then
    echo "PASS: $name"; ((PASS++)) || true
  else
    echo "FAIL: $name (expected '$expected', got '$actual')"; ((FAIL++)) || true
  fi
}

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
HOME="$TMP/home"
CODEX_HOME="$TMP/codex"
export HOME CODEX_HOME
mkdir -p "$HOME"

# --- user-style install (CODEX_HOME + ~/.agents/skills) ---
bash "$LIB" install >/dev/null
check "manifest written" "yes" "$([[ -f "$CODEX_HOME/loop-spec-install.json" ]] && echo yes || echo no)"
check "manifest uses plugin version" \
  "$(jq -r '.version' "$REPO/.codex-plugin/plugin.json")" \
  "$(jq -r '.version' "$CODEX_HOME/loop-spec-install.json")"

check "namespaced cycle skill generated" "yes" "$([[ -f "$HOME/.agents/skills/loop-spec-cycle/SKILL.md" ]] && echo yes || echo no)"
check "namespaced auto skill generated" "yes" "$([[ -f "$HOME/.agents/skills/loop-spec-auto/SKILL.md" ]] && echo yes || echo no)"
check "namespaced skill frontmatter" "1" "$(grep -c '^name: loop-spec-cycle$' "$HOME/.agents/skills/loop-spec-cycle/SKILL.md")"
check "source skill remains unshadowed" "no" "$([[ -e "$HOME/.agents/skills/cycle" ]] && echo yes || echo no)"
check "skill adapter loads Codex contract" "yes" "$(grep -q 'codex-harness.md' "$HOME/.agents/skills/loop-spec-cycle/SKILL.md" && echo yes || echo no)"
check "skill adapter disables implicit invocation" "1" "$(grep -c '^allow_implicit_invocation: false$' "$HOME/.agents/skills/loop-spec-cycle/SKILL.md")"
skill_count="$(find "$HOME/.agents/skills" -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ')"
repo_skill_count="$(ls -d "$REPO"/skills/*/SKILL.md | wc -l | tr -d ' ')"
check "every SKILL.md has a namespaced adapter" "$repo_skill_count" "$skill_count"

check "implementer agent generated" "yes" "$([[ -f "$CODEX_HOME/agents/loop-spec-implementer.toml" ]] && echo yes || echo no)"
check "readonly agent generated" "yes" "$([[ -f "$CODEX_HOME/agents/loop-spec-readonly.toml" ]] && echo yes || echo no)"
check "agent is a real file (not link)" "no" "$([[ -L "$CODEX_HOME/agents/loop-spec-implementer.toml" ]] && echo yes || echo no)"
check "agent name field" "1" "$(grep -c '^name = "loop-spec-implementer"$' "$CODEX_HOME/agents/loop-spec-implementer.toml")"
check "readonly sandbox" "1" "$(grep -c '^sandbox_mode = "read-only"$' "$CODEX_HOME/agents/loop-spec-readonly.toml")"
check "agent carries GENERATED marker" "yes" "$(grep -q "GENERATED by loop-spec's lib/codex-install.sh" "$CODEX_HOME/agents/loop-spec-implementer.toml" && echo yes || echo no)"

check "config env block" "yes" "$(grep -q '# BEGIN loop-spec' "$CODEX_HOME/config.toml" && echo yes || echo no)"
check "config sets harness" "1" "$(grep -c 'LOOP_SPEC_HARNESS = "codex"' "$CODEX_HOME/config.toml")"
check "config sets plugin root" "yes" "$(grep -q "$REPO" "$CODEX_HOME/config.toml" && echo yes || echo no)"
check "hooks.json written" "yes" "$([[ -f "$CODEX_HOME/hooks.json" ]] && echo yes || echo no)"
check "hooks call session-start" "yes" "$(grep -q 'codex-session-start.sh' "$CODEX_HOME/hooks.json" && echo yes || echo no)"
check "user install does not write a marketplace outside the clone" "no" "$([[ -f "$HOME/.agents/plugins/marketplace.json" ]] && echo yes || echo no)"

# --model routes land in generated TOML
bash "$LIB" install --model adversarial=gpt-5.4 --model planner=o3 >/dev/null
check "planner model route" "1" "$(grep -c '^model = "o3"$' "$CODEX_HOME/agents/loop-spec-planner.toml")"
check "challenger inherits adversarial" "1" "$(grep -c '^model = "gpt-5.4"$' "$CODEX_HOME/agents/loop-spec-challenger.toml")"
check "implementer unrouted has no model" "0" "$(grep -c '^model =' "$CODEX_HOME/agents/loop-spec-implementer.toml" || true)"

# --- project-style install ---
PROJ="$TMP/proj"
mkdir -p "$PROJ"
bash "$LIB" install --project "$PROJ" >/dev/null
check "project skill adapter" "yes" "$([[ -f "$PROJ/.agents/skills/loop-spec-cycle/SKILL.md" ]] && echo yes || echo no)"
check "project agent" "yes" "$([[ -f "$PROJ/.codex/agents/loop-spec-verifier.toml" ]] && echo yes || echo no)"
check "project config CLAUDE_PROJECT_DIR" "yes" "$(grep -q "$PROJ" "$PROJ/.codex/config.toml" && echo yes || echo no)"
check "foreign project has no marketplace" "no" "$([[ -f "$PROJ/.agents/plugins/marketplace.json" ]] && echo yes || echo no)"

# --- status + uninstall ---
out="$(CODEX_HOME="$CODEX_HOME" HOME="$HOME" bash "$LIB" status)"
check "status reports installed" "yes" "$(grep -q "^installed:" <<<"$out" && echo yes || echo no)"
CODEX_HOME="$CODEX_HOME" HOME="$HOME" bash "$LIB" uninstall >/dev/null
check "uninstall removes manifest" "no" "$([[ -f "$CODEX_HOME/loop-spec-install.json" ]] && echo yes || echo no)"
check "uninstall removes adapters" "no" "$([[ -f "$HOME/.agents/skills/loop-spec-cycle/SKILL.md" ]] && echo yes || echo no)"
check "uninstall removes agents" "no" "$([[ -f "$CODEX_HOME/agents/loop-spec-implementer.toml" ]] && echo yes || echo no)"
check "uninstall strips env block" "0" "$(if [[ -f "$CODEX_HOME/config.toml" ]] && grep -q 'BEGIN loop-spec' "$CODEX_HOME/config.toml"; then echo 1; else echo 0; fi)"

echo ""
echo "Results: $PASS passed, $FAIL failed"
[[ "$FAIL" -eq 0 ]]
