#!/usr/bin/env bash
# Tests for lib/codex-install.sh — install into a temp Codex home and assert
# skills, custom agents, env, and hooks land on the documented discovery
# surfaces; manifest-driven uninstall removes exactly its own.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
LIB="$REPO/lib/codex-install.sh"
PASS=0
FAIL=0

check() {
  local name="$1" expected="$2" actual="$3"
  if [[ "$actual" == "$expected" ]]; then
    echo "PASS: $name"; ((PASS++)) || true
  else
    echo "FAIL: $name (expected '$expected', got '$actual')"; ((FAIL++)) || true
  fi
}

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
HOME="$TMP/home"
CODEX_HOME="$TMP/codex"
export HOME CODEX_HOME
mkdir -p "$HOME"
mkdir -p "$CODEX_HOME"
cat > "$CODEX_HOME/config.toml" <<'EOF'
model = "keep-me"

[shell_environment_policy.set]
USER_SETTING = "preserved"
EOF
cat > "$CODEX_HOME/hooks.json" <<'EOF'
{
  "custom": "preserved",
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "Bash",
        "hooks": [
          {"type": "command", "command": "echo user-hook", "statusMessage": "user hook"}
        ]
      }
    ]
  }
}
EOF

# Invalid merged state fails before any generated artifacts are placed.
BAD_HOME="$TMP/bad-home"
BAD_CODEX="$TMP/bad-codex"
mkdir -p "$BAD_HOME" "$BAD_CODEX"
printf '{not-json\n' > "$BAD_CODEX/hooks.json"
set +e
HOME="$BAD_HOME" CODEX_HOME="$BAD_CODEX" bash "$LIB" install >/dev/null 2>&1
bad_rc=$?
set -e
check "invalid hooks fail preflight" "2" "$bad_rc"
check "invalid hooks create no agents" "no" "$([[ -e "$BAD_CODEX/agents/loop-spec-implementer.toml" ]] && echo yes || echo no)"
check "invalid hooks are preserved" "{not-json" "$(tr -d '\n' < "$BAD_CODEX/hooks.json")"

# --- user-style install (CODEX_HOME + ~/.agents/skills) ---
bash "$LIB" install >/dev/null
check "manifest written" "yes" "$([[ -f "$CODEX_HOME/loop-spec-install.json" ]] && echo yes || echo no)"
check "manifest uses plugin version" \
  "$(jq -r '.version' "$REPO/.codex-plugin/plugin.json")" \
  "$(jq -r '.version' "$CODEX_HOME/loop-spec-install.json")"

check "namespaced cycle skill generated" "yes" "$([[ -f "$HOME/.agents/skills/loop-spec-cycle/SKILL.md" ]] && echo yes || echo no)"
check "namespaced auto skill generated" "yes" "$([[ -f "$HOME/.agents/skills/loop-spec-auto/SKILL.md" ]] && echo yes || echo no)"
check "namespaced skill frontmatter" "1" "$(grep -c '^name: loop-spec-cycle$' "$HOME/.agents/skills/loop-spec-cycle/SKILL.md")"
check "source skill remains unshadowed" "no" "$([[ -e "$HOME/.agents/skills/cycle" ]] && echo yes || echo no)"
check "skill adapter loads Codex contract" "yes" "$(grep -q 'codex-harness.md' "$HOME/.agents/skills/loop-spec-cycle/SKILL.md" && echo yes || echo no)"
check "skill adapter re-exports source directory" "1" "$(grep -c "^export CLAUDE_SKILL_DIR=$REPO/skills/cycle$" "$HOME/.agents/skills/loop-spec-cycle/SKILL.md")"
check "skill invocation policy is outside SKILL.md" "0" "$(grep -c '^allow_implicit_invocation:' "$HOME/.agents/skills/loop-spec-cycle/SKILL.md" || true)"
check "skill adapter writes OpenAI metadata" "yes" "$([[ -f "$HOME/.agents/skills/loop-spec-cycle/agents/openai.yaml" ]] && echo yes || echo no)"
check "skill adapter disables implicit invocation" "1" "$(grep -c '^  allow_implicit_invocation: false$' "$HOME/.agents/skills/loop-spec-cycle/agents/openai.yaml")"
skill_count="$(find "$HOME/.agents/skills" -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ')"
repo_skill_count="$(ls -d "$REPO"/skills/*/SKILL.md | wc -l | tr -d ' ')"
check "every SKILL.md has a namespaced adapter" "$repo_skill_count" "$skill_count"
check "local-script skill uses its own source directory" "1" "$(grep -c "^export CLAUDE_SKILL_DIR=$REPO/skills/loop-runner$" "$HOME/.agents/skills/loop-spec-loop-runner/SKILL.md")"

check "implementer agent generated" "yes" "$([[ -f "$CODEX_HOME/agents/loop-spec-implementer.toml" ]] && echo yes || echo no)"
check "readonly agent generated" "yes" "$([[ -f "$CODEX_HOME/agents/loop-spec-readonly.toml" ]] && echo yes || echo no)"
check "agent is a real file (not link)" "no" "$([[ -L "$CODEX_HOME/agents/loop-spec-implementer.toml" ]] && echo yes || echo no)"
check "agent name field" "1" "$(grep -c '^name = "loop-spec-implementer"$' "$CODEX_HOME/agents/loop-spec-implementer.toml")"
check "readonly sandbox" "1" "$(grep -c '^sandbox_mode = "read-only"$' "$CODEX_HOME/agents/loop-spec-readonly.toml")"
check "agent carries GENERATED marker" "yes" "$(grep -q "GENERATED by loop-spec's lib/codex-install.sh" "$CODEX_HOME/agents/loop-spec-implementer.toml" && echo yes || echo no)"

check "config env block" "yes" "$(grep -q '# BEGIN loop-spec' "$CODEX_HOME/config.toml" && echo yes || echo no)"
check "config sets harness" "1" "$(grep -c 'LOOP_SPEC_HARNESS = "codex"' "$CODEX_HOME/config.toml")"
check "config sets plugin root" "yes" "$(grep -q "$REPO" "$CODEX_HOME/config.toml" && echo yes || echo no)"
check "config keeps one env table" "1" "$(grep -c '^\[shell_environment_policy.set\]$' "$CODEX_HOME/config.toml")"
check "config preserves user setting" "1" "$(grep -c '^USER_SETTING = "preserved"$' "$CODEX_HOME/config.toml")"
check "hooks.json written" "yes" "$([[ -f "$CODEX_HOME/hooks.json" ]] && echo yes || echo no)"
check "hooks call session-start" "yes" "$(grep -q 'codex-session-start.sh' "$CODEX_HOME/hooks.json" && echo yes || echo no)"
check "hooks preserve user command" "1" "$(grep -c 'echo user-hook' "$CODEX_HOME/hooks.json")"
check "manifest excludes merged config" "0" "$(jq --arg p "$CODEX_HOME/config.toml" '[.created[] | select(. == $p)] | length' "$CODEX_HOME/loop-spec-install.json")"
check "manifest tracks merged config" "1" "$(jq --arg p "$CODEX_HOME/config.toml" '[.managed[] | select(.path == $p and .kind == "config")] | length' "$CODEX_HOME/loop-spec-install.json")"
check "user install does not write a marketplace outside the clone" "no" "$([[ -f "$HOME/.agents/plugins/marketplace.json" ]] && echo yes || echo no)"

# --model routes land in generated TOML
bash "$LIB" install --model adversarial=gpt-5.6 --model planner=gpt-5.6-terra >/dev/null
check "planner model route" "1" "$(grep -c '^model = "gpt-5.6-terra"$' "$CODEX_HOME/agents/loop-spec-planner.toml")"
check "challenger inherits adversarial" "1" "$(grep -c '^model = "gpt-5.6"$' "$CODEX_HOME/agents/loop-spec-challenger.toml")"
check "implementer unrouted has no model" "0" "$(grep -c '^model =' "$CODEX_HOME/agents/loop-spec-implementer.toml" || true)"

# --- project-style install ---
PROJ="$TMP/proj"
mkdir -p "$PROJ"
bash "$LIB" install --project "$PROJ" >/dev/null
check "project skill adapter" "yes" "$([[ -f "$PROJ/.agents/skills/loop-spec-cycle/SKILL.md" ]] && echo yes || echo no)"
check "project agent" "yes" "$([[ -f "$PROJ/.codex/agents/loop-spec-verifier.toml" ]] && echo yes || echo no)"
check "project config CLAUDE_PROJECT_DIR" "yes" "$(grep -q "$PROJ" "$PROJ/.codex/config.toml" && echo yes || echo no)"
check "foreign project has no marketplace" "no" "$([[ -f "$PROJ/.agents/plugins/marketplace.json" ]] && echo yes || echo no)"
HOME="$HOME" CODEX_HOME="$CODEX_HOME" bash "$LIB" uninstall --project "$PROJ" >/dev/null
check "project uninstall removes created config" "no" "$([[ -f "$PROJ/.codex/config.toml" ]] && echo yes || echo no)"
check "project uninstall removes created hooks" "no" "$([[ -f "$PROJ/.codex/hooks.json" ]] && echo yes || echo no)"

# --- status + uninstall ---
out="$(CODEX_HOME="$CODEX_HOME" HOME="$HOME" bash "$LIB" status)"
check "status reports installed" "yes" "$(grep -q "^installed:" <<<"$out" && echo yes || echo no)"
CODEX_HOME="$CODEX_HOME" HOME="$HOME" bash "$LIB" uninstall >/dev/null
check "uninstall removes manifest" "no" "$([[ -f "$CODEX_HOME/loop-spec-install.json" ]] && echo yes || echo no)"
check "uninstall removes adapters" "no" "$([[ -f "$HOME/.agents/skills/loop-spec-cycle/SKILL.md" ]] && echo yes || echo no)"
check "uninstall removes agents" "no" "$([[ -f "$CODEX_HOME/agents/loop-spec-implementer.toml" ]] && echo yes || echo no)"
check "uninstall strips env block" "0" "$(if [[ -f "$CODEX_HOME/config.toml" ]] && grep -q 'BEGIN loop-spec' "$CODEX_HOME/config.toml"; then echo 1; else echo 0; fi)"
check "uninstall preserves config" "1" "$(grep -c '^model = "keep-me"$' "$CODEX_HOME/config.toml")"
check "uninstall preserves env setting" "1" "$(grep -c '^USER_SETTING = "preserved"$' "$CODEX_HOME/config.toml")"
check "uninstall preserves hooks file" "yes" "$([[ -f "$CODEX_HOME/hooks.json" ]] && echo yes || echo no)"
check "uninstall preserves user hook" "1" "$(grep -c 'echo user-hook' "$CODEX_HOME/hooks.json")"
check "uninstall removes only owned hooks" "0" "$(grep -c 'loop-spec ' "$CODEX_HOME/hooks.json" || true)"

echo ""
echo "Results: $PASS passed, $FAIL failed"
[[ "$FAIL" -eq 0 ]]
