#!/usr/bin/env bash
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"; WORK="$(mktemp -d "${TMPDIR:-/tmp}/okf-handoff.XXXXXX")"; trap 'rm -rf "$WORK"' EXIT
PASS=0; FAIL=0
check() { local n="$1" e="$2" a="$3"; if [[ "$e" == "$a" ]]; then echo "PASS: $n"; PASS=$((PASS+1)); else echo "FAIL: $n (expected '$e', got '$a')"; FAIL=$((FAIL+1)); fi; }
REPO="$WORK/repo"; mkdir -p "$REPO"; git -C "$REPO" init -q -b main; git -C "$REPO" config user.name Test; git -C "$REPO" config user.email test@example.com; git -C "$REPO" commit -q --allow-empty -m init
export LOOP_SPEC_HARNESS=codex LOOP_SPEC_TEAMS_MODE=none LOOP_SPEC_WORKFLOWS_AVAILABLE=0 LOOP_SPEC_CHECKPOINT_PR=0
bash "$ROOT/lib/cycle-driver.sh" start --dir "$REPO" -- okf handoff >/dev/null 2>&1; bash "$ROOT/lib/cycle-driver.sh" init --dir "$REPO" --slug okf-handoff --title 'okf handoff' --style auto --profile standard --autonomous 0 >/dev/null 2>&1
FD="$REPO/.loop-spec/features/okf-handoff"; DOCS="$REPO/docs/loop-spec/features/okf-handoff"; mkdir -p "$DOCS"; cp "$ROOT/tests/fixtures/minimal-SPEC.md" "$DOCS/SPEC.md"
before_feature="$(shasum -a 256 "$FD/feature.json" | cut -d' ' -f1)"; before_head="$(git -C "$REPO" rev-parse HEAD)"; before_tags="$(git -C "$REPO" tag)"
rc=0; bash "$ROOT/lib/phase-exit.sh" spec --feature-dir "$FD" --check >/dev/null 2>&1 || rc=$?; check "SPEC --check passes" 0 "$rc"; check "SPEC --check does not create index" 0 "$([[ -e "$DOCS/index.md" ]] && echo 1 || echo 0)"; check "SPEC --check preserves feature state" "$before_feature" "$(shasum -a 256 "$FD/feature.json" | cut -d' ' -f1)"; check "SPEC --check preserves HEAD" "$before_head" "$(git -C "$REPO" rev-parse HEAD)"; check "SPEC --check preserves tags" "$before_tags" "$(git -C "$REPO" tag)"
rc=0; bash "$ROOT/lib/phase-exit.sh" spec --feature-dir "$FD" >/dev/null 2>&1 || rc=$?; check "SPEC exit succeeds" 0 "$rc"; check "phase exit publishes index" 1 "$([[ -f "$DOCS/index.md" ]] && echo 1 || echo 0)"; check "index has root version and no type" 1 "$(grep -q '^okf_version: "0.2"$' "$DOCS/index.md" && ! grep -q '^type:' "$DOCS/index.md" && echo 1 || echo 0)"; check "index commit is published" 1 "$(git -C "$REPO" show --format= --name-only HEAD | grep -c 'docs/loop-spec/features/okf-handoff/index.md')"; check "index lists SPEC" 1 "$(grep -c 'SPEC.md' "$DOCS/index.md")"
entry="$(bash "$ROOT/lib/phase-entry.sh" spec --feature-dir "$FD" 2>&1 || true)"; check "phase entry exposes index" 1 "$(grep -c '^index=.*index.md$' <<<"$entry")"; check "index is optional in phase required reads" 1 "$(grep -c 'phase-entry: ok (spec)' <<<"$entry")"
printf '%s\n' '---' 'type: Pattern Index' '---' '# PATTERNS' > "$DOCS/PATTERNS.md"; printf '%s\n' '---' 'type: Implementation Plan' '---' '# PLAN' > "$DOCS/PLAN.md"; bash "$ROOT/lib/okf.sh" index "$DOCS" >/dev/null; index_hash="$(shasum -a 256 "$DOCS/index.md" | cut -d' ' -f1)"; bash "$ROOT/lib/okf.sh" index "$DOCS" >/dev/null; check "typed PLAN/PATTERNS index is idempotent" 1 "$(grep -q 'PATTERNS.md' "$DOCS/index.md" && grep -q 'PLAN.md' "$DOCS/index.md" && [[ "$index_hash" == "$(shasum -a 256 "$DOCS/index.md" | cut -d' ' -f1)" ]] && echo 1 || echo 0)"
bad_index="$(shasum -a 256 "$DOCS/index.md" | cut -d' ' -f1)"; bad_feature="$(shasum -a 256 "$FD/feature.json" | cut -d' ' -f1)"; bad_head="$(git -C "$REPO" rev-parse HEAD)"; bad_tags="$(git -C "$REPO" tag)"
cp "$DOCS/SPEC.md" "$DOCS/SPEC.bad.md"; sed 's/^type: Specification$/type: Wrong/' "$DOCS/SPEC.bad.md" > "$DOCS/SPEC.md"; rc=0; bash "$ROOT/lib/phase-exit.sh" spec --feature-dir "$FD" --check >/dev/null 2>&1 || rc=$?; check "wrong type rejects" 1 "$([[ $rc != 0 ]] && echo 1 || echo 0)"; check "wrong type preserves index" "$bad_index" "$(shasum -a 256 "$DOCS/index.md" | cut -d' ' -f1)"; check "wrong type preserves state" "$bad_feature" "$(shasum -a 256 "$FD/feature.json" | cut -d' ' -f1)"; check "wrong type preserves HEAD" "$bad_head" "$(git -C "$REPO" rev-parse HEAD)"; check "wrong type preserves tags" "$bad_tags" "$(git -C "$REPO" tag)"
echo "Results: $PASS passed, $FAIL failed"; [[ "$FAIL" -eq 0 ]]
