#!/usr/bin/env bash
# adk-install.sh - Mount loop-spec into a Google ADK project.
#
# ADK is a framework, not a coding agent: nothing runs until an app builds an
# agent. This writes that mount — two agent directories in the caller's project,
# each a small shim over the checked-in package in extensions/adk/:
#
#   <mount>/loop_spec/agent.py           the working agent (shell, files, skills,
#                                        dispatch_subagent)
#   <mount>/loop_spec_readonly/agent.py  the judge / spec-compiler agent
#                                        (ReadFile and skills only)
#
# `adk run <dir>` loads a module-level `app` before `root_agent`, and only the
# App form carries the lifecycle plugin, so both shims expose `app`.
#
# The shims point at THIS clone by absolute path rather than copying the package.
# A generated copy would be an unversioned fork that drifts from the source tree
# the moment either side changes; a path reference means `git pull` updates the
# behavior, which is the property the opencode installer gets from symlinking.
#
# Usage:
#   adk-install.sh install [--project <dir>] [--mount <subdir>] [--model <id>]
#   adk-install.sh check   [--project <dir>] [--mount <subdir>]
#   adk-install.sh uninstall [--project <dir>] [--mount <subdir>]
#
#   --project  ADK project root (default: cwd)
#   --mount    subdirectory to write the agents into (default: adk_agents)
#   --model    default ADK model for both agents (default: gemini-2.5-pro, or
#              $LOOP_SPEC_ADK_MODEL). Per-role models come from agents/*.md when
#              they name an ADK id; `inherit` and Claude aliases fall back here.
#
# Exit codes: 0 ok; 1 install/check failure; 2 bad invocation.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PKG="$ROOT/extensions/adk"

_die2() { echo "adk-install: $*" >&2; exit 2; }
_fail() { echo "adk-install: $*" >&2; exit 1; }

cmd="${1:-}"
case "$cmd" in install|check|uninstall) shift ;; *)
  _die2 "unknown subcommand '${cmd:-}' (usage: adk-install.sh install|check|uninstall [--project <dir>] [--mount <subdir>] [--model <id>])" ;;
esac

PROJECT="$PWD"
MOUNT="adk_agents"
MODEL="${LOOP_SPEC_ADK_MODEL:-gemini-2.5-pro}"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --project) PROJECT="${2:-}"; shift 2 || shift ;;
    --mount)   MOUNT="${2:-}"; shift 2 || shift ;;
    --model)   MODEL="${2:-}"; shift 2 || shift ;;
    *) _die2 "unknown option '$1'" ;;
  esac
done
[[ -n "$PROJECT" && -d "$PROJECT" ]] || _die2 "--project '$PROJECT' is not a directory"
[[ -n "$MOUNT" ]] || _die2 "--mount must not be empty"
command -v python3 >/dev/null 2>&1 || _fail "python3 >= 3.10 is required"
PROJECT="$(cd "$PROJECT" && pwd)"
MOUNT_DIR="$(python3 - "$PROJECT" "$MOUNT" <<'PY'
import os, sys
project = os.path.realpath(sys.argv[1])
candidate = os.path.realpath(os.path.join(project, sys.argv[2]))
if os.path.isabs(sys.argv[2]) or candidate == project or os.path.commonpath((project, candidate)) != project:
    raise SystemExit(1)
print(candidate)
PY
)" || _die2 "--mount must name a subdirectory inside --project (got '$MOUNT')"
AGENT_DIR="$MOUNT_DIR/loop_spec"
READONLY_DIR="$MOUNT_DIR/loop_spec_readonly"
GENERATED_MARKER="# GENERATED by loop-spec lib/adk-install.sh; edit the installer, not this file."
ADK_REQUIREMENT=">=2.7,<3"

compatible_adk_version() {
  python3 - "$ADK_REQUIREMENT" <<'PY'
import sys
from importlib.metadata import PackageNotFoundError, version

requirement = sys.argv[1]
try:
    installed = version("google-adk")
except PackageNotFoundError:
    print("google-adk is not installed", file=sys.stderr)
    raise SystemExit(1)

try:
    from packaging.specifiers import SpecifierSet
except ImportError:
    print("the packaging module is required to validate google-adk", file=sys.stderr)
    raise SystemExit(1)

if not SpecifierSet(requirement).contains(installed, prereleases=True):
    print(f"google-adk {installed} does not satisfy {requirement}", file=sys.stderr)
    raise SystemExit(1)

try:
    import google.adk  # noqa: F401
except Exception as exc:
    print(f"google-adk {installed} is not importable: {exc}", file=sys.stderr)
    raise SystemExit(1)

print(installed)
PY
}

is_generated() { # is_generated <file>
  [[ -f "$1" ]] && grep -qF "$GENERATED_MARKER" "$1"
}

write_shim() { # write_shim <dir> <readonly:true|false>
  local dir="$1" readonly="$2"
  mkdir -p "$dir"
  # __init__.py so `adk run` can also load the folder as a package.
  printf '%s\nfrom .agent import app  # noqa: F401\n' "$GENERATED_MARKER" > "$dir/__init__.py"
  python3 - "$dir/agent.py" "$ROOT" "$PROJECT" "$MOUNT" "$PKG" "$MODEL" "$readonly" <<'PY'
import sys

output, root, project, mount, package, model, readonly = sys.argv[1:]
content = f'''# GENERATED by loop-spec lib/adk-install.sh; edit the installer, not this file.
"""Google ADK mount generated by loop-spec.

Regenerate with:
    bash {root!r}/lib/adk-install.sh install --project {project!r} --mount {mount!r}
"""

import sys

_PACKAGE_PATH = {package!r}
if _PACKAGE_PATH not in sys.path:
    sys.path.insert(0, _PACKAGE_PATH)

from loop_spec_adk import build_app  # noqa: E402

MODEL = {model!r}

app = build_app({project!r}, model=MODEL, readonly={readonly == "True"!r})
root_agent = app.root_agent
'''
with open(output, "w", encoding="utf-8") as f:
    f.write(content)
PY
}

case "$cmd" in
  install)
    [[ -d "$PKG/loop_spec_adk" ]] || _fail "package payload missing at $PKG/loop_spec_adk"
    command -v jq >/dev/null 2>&1 || _fail "jq >= 1.5 is required"
    ADK_VERSION="$(compatible_adk_version)" \
      || _fail "google-adk must satisfy '$ADK_REQUIREMENT' in the python3 environment"
    for target in "$AGENT_DIR/__init__.py" "$AGENT_DIR/agent.py" \
                  "$READONLY_DIR/__init__.py" "$READONLY_DIR/agent.py"; do
      if [[ -e "$target" ]] && ! is_generated "$target"; then
        _fail "refusing to overwrite existing non-loop-spec file: $target"
      fi
    done
    write_shim "$AGENT_DIR" "False"
    write_shim "$READONLY_DIR" "True"

    mkdir -p "$PROJECT/.loop-spec"
    jq -n --arg agent "$AGENT_DIR" --arg readonly "$READONLY_DIR" \
          --arg model "$MODEL" --arg package "$ROOT" --arg mount "$MOUNT" \
          --arg adk_version "$ADK_VERSION" --arg adk_requirement "$ADK_REQUIREMENT" \
      '{harness:"adk", agentDir:$agent, readonlyAgentDir:$readonly,
        model:$model, packageRoot:$package, mount:$mount,
        adkVersion:$adk_version, adkRequirement:$adk_requirement}' \
      > "$PROJECT/.loop-spec/adk-install.json"

    echo "loop-spec mounted for ADK:"
    echo "  agent:     $AGENT_DIR"
    echo "  read-only: $READONLY_DIR"
    echo "  model:     $MODEL"
    echo
    echo "Run it:      adk run \"$AGENT_DIR\" \"<task>\" --jsonl"
    echo "Fleet + intake need the agent directory on the environment:"
    echo "  export LOOP_SPEC_ADK_AGENT_DIR=\"$AGENT_DIR\""
    ;;

  check)
    status=0
    if ! ADK_VERSION="$(compatible_adk_version)"; then
      echo "adk-install: google-adk must satisfy '$ADK_REQUIREMENT' in the python3 environment" >&2
      status=1
    fi
    for d in "$AGENT_DIR" "$READONLY_DIR"; do
      [[ -f "$d/agent.py" ]] || { echo "adk-install: missing $d/agent.py" >&2; status=1; }
      [[ -f "$d/__init__.py" ]] || { echo "adk-install: missing $d/__init__.py" >&2; status=1; }
      if [[ -f "$d/agent.py" ]] && ! is_generated "$d/agent.py"; then
        echo "adk-install: $d/agent.py is not owned by this installer" >&2; status=1
      fi
    done
    # A shim pointing at a package root that no longer exists is the drift this
    # catches: the clone moved or was deleted and every dispatch would ImportError.
    for shim in "$AGENT_DIR/agent.py" "$READONLY_DIR/agent.py"; do
      [[ -f "$shim" ]] || continue
      pkg="$(python3 - "$shim" <<'PY'
import ast, pathlib, sys
try:
    tree = ast.parse(pathlib.Path(sys.argv[1]).read_text(encoding="utf-8"))
    value = next(n.value for n in tree.body if isinstance(n, ast.Assign)
                 and any(isinstance(t, ast.Name) and t.id == "_PACKAGE_PATH" for t in n.targets))
    print(ast.literal_eval(value))
except Exception:
    raise SystemExit(1)
PY
)" || { echo "adk-install: cannot read _PACKAGE_PATH from $shim" >&2; status=1; continue; }
      if [[ ! -d "$pkg/loop_spec_adk" ]]; then
        echo "adk-install: $shim points at '$pkg', which is gone — re-run install" >&2
        status=1
      fi
    done
    [[ "$status" -eq 0 ]] && echo "adk-install: mount OK ($AGENT_DIR)"
    exit "$status"
    ;;

  uninstall)
    status=0
    for d in "$AGENT_DIR" "$READONLY_DIR"; do
      for target in "$d/agent.py" "$d/__init__.py"; do
        [[ -e "$target" ]] || continue
        if is_generated "$target"; then
          rm -f "$target"
        else
          echo "adk-install: preserving non-loop-spec file: $target" >&2
          status=1
        fi
      done
      rmdir "$d" 2>/dev/null || {
        if [[ -d "$d" ]]; then
          echo "adk-install: preserving non-empty directory: $d" >&2
          status=1
        fi
      }
    done
    if [[ -f "$PROJECT/.loop-spec/adk-install.json" ]] \
       && jq -e '.harness == "adk"' "$PROJECT/.loop-spec/adk-install.json" >/dev/null 2>&1; then
      rm -f "$PROJECT/.loop-spec/adk-install.json"
    fi
    rmdir "$PROJECT/.loop-spec" 2>/dev/null || true
    rmdir "$MOUNT_DIR" 2>/dev/null || true
    if [[ "$status" -eq 0 ]]; then
      echo "adk-install: removed generated loop-spec ADK files under $MOUNT_DIR"
    else
      echo "adk-install: uninstall incomplete; unrelated files were preserved" >&2
    fi
    exit "$status"
    ;;
esac
