#!/usr/bin/env bash
# adk-install.sh - Mount loop-spec into a Google ADK project.
#
# ADK is a framework, not a coding agent: nothing runs until an app builds an
# agent. This writes that mount — two agent directories in the caller's project,
# each a small shim over the checked-in package in extensions/adk/:
#
#   <mount>/loop_spec/agent.py           the working agent (shell, files, skills,
#                                        dispatch_subagent)
#   <mount>/loop_spec_readonly/agent.py  the judge / spec-compiler agent
#                                        (ReadFile and skills only)
#
# `adk run <dir>` loads a module-level `app` before `root_agent`, and only the
# App form carries the lifecycle plugin, so both shims expose `app`.
#
# The shims point at THIS clone by absolute path rather than copying the package.
# A generated copy would be an unversioned fork that drifts from the source tree
# the moment either side changes; a path reference means `git pull` updates the
# behavior, which is the property the opencode installer gets from symlinking.
#
# Usage:
#   adk-install.sh install [--project <dir>] [--mount <subdir>] [--model <id>]
#   adk-install.sh check   [--project <dir>] [--mount <subdir>]
#   adk-install.sh uninstall [--project <dir>] [--mount <subdir>]
#
#   --project  ADK project root (default: cwd)
#   --mount    subdirectory to write the agents into (default: adk_agents)
#   --model    default ADK model for both agents (default: gemini-2.5-pro, or
#              $LOOP_SPEC_ADK_MODEL). Per-role models come from agents/*.md when
#              they name an ADK id; `inherit` and Claude aliases fall back here.
#
# Exit codes: 0 ok; 1 install/check failure; 2 bad invocation.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PKG="$ROOT/extensions/adk"

_die2() { echo "adk-install: $*" >&2; exit 2; }
_fail() { echo "adk-install: $*" >&2; exit 1; }

cmd="${1:-}"
case "$cmd" in install|check|uninstall) shift ;; *)
  _die2 "unknown subcommand '${cmd:-}' (usage: adk-install.sh install|check|uninstall [--project <dir>] [--mount <subdir>] [--model <id>])" ;;
esac

PROJECT="$PWD"
MOUNT="adk_agents"
MODEL="${LOOP_SPEC_ADK_MODEL:-gemini-2.5-pro}"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --project) PROJECT="${2:-}"; shift 2 || shift ;;
    --mount)   MOUNT="${2:-}"; shift 2 || shift ;;
    --model)   MODEL="${2:-}"; shift 2 || shift ;;
    *) _die2 "unknown option '$1'" ;;
  esac
done
[[ -n "$PROJECT" && -d "$PROJECT" ]] || _die2 "--project '$PROJECT' is not a directory"
[[ -n "$MOUNT" ]] || _die2 "--mount must not be empty"
PROJECT="$(cd "$PROJECT" && pwd)"
MOUNT_DIR="$PROJECT/$MOUNT"
AGENT_DIR="$MOUNT_DIR/loop_spec"
READONLY_DIR="$MOUNT_DIR/loop_spec_readonly"

write_shim() { # write_shim <dir> <readonly:true|false>
  local dir="$1" readonly="$2"
  mkdir -p "$dir"
  # __init__.py so `adk run` can also load the folder as a package.
  printf 'from .agent import app  # noqa: F401\n' > "$dir/__init__.py"
  cat > "$dir/agent.py" <<PY
"""Generated by loop-spec lib/adk-install.sh — edit the model, not the wiring.

Regenerate with:
    bash "$ROOT/lib/adk-install.sh" install --project "$PROJECT" --mount "$MOUNT"
"""

import sys

_PACKAGE_PATH = r"$PKG"
if _PACKAGE_PATH not in sys.path:
    sys.path.insert(0, _PACKAGE_PATH)

from loop_spec_adk import build_app  # noqa: E402

MODEL = "$MODEL"

app = build_app(r"$PROJECT", model=MODEL, readonly=$readonly)
root_agent = app.root_agent
PY
}

case "$cmd" in
  install)
    [[ -d "$PKG/loop_spec_adk" ]] || _fail "package payload missing at $PKG/loop_spec_adk"
    command -v python3 >/dev/null 2>&1 || _fail "python3 is required"
    if ! python3 -c "import google.adk" >/dev/null 2>&1; then
      echo "adk-install: warning — google-adk is not importable by python3." >&2
      echo "             Install it in the environment that runs the agent: pip install google-adk" >&2
    fi

    write_shim "$AGENT_DIR" "False"
    write_shim "$READONLY_DIR" "True"

    mkdir -p "$PROJECT/.loop-spec"
    jq -n --arg agent "$AGENT_DIR" --arg readonly "$READONLY_DIR" \
          --arg model "$MODEL" --arg package "$ROOT" --arg mount "$MOUNT" \
      '{harness:"adk", agentDir:$agent, readonlyAgentDir:$readonly,
        model:$model, packageRoot:$package, mount:$mount}' \
      > "$PROJECT/.loop-spec/adk-install.json"

    echo "loop-spec mounted for ADK:"
    echo "  agent:     $AGENT_DIR"
    echo "  read-only: $READONLY_DIR"
    echo "  model:     $MODEL"
    echo
    echo "Run it:      adk run \"$AGENT_DIR\" \"<task>\" --jsonl"
    echo "Fleet + intake need the agent directory on the environment:"
    echo "  export LOOP_SPEC_ADK_AGENT_DIR=\"$AGENT_DIR\""
    ;;

  check)
    status=0
    for d in "$AGENT_DIR" "$READONLY_DIR"; do
      [[ -f "$d/agent.py" ]] || { echo "adk-install: missing $d/agent.py" >&2; status=1; }
    done
    # A shim pointing at a package root that no longer exists is the drift this
    # catches: the clone moved or was deleted and every dispatch would ImportError.
    if [[ -f "$AGENT_DIR/agent.py" ]]; then
      pkg="$(sed -n 's/^_PACKAGE_PATH = r"\(.*\)"$/\1/p' "$AGENT_DIR/agent.py" | head -1)"
      if [[ -n "$pkg" && ! -d "$pkg/loop_spec_adk" ]]; then
        echo "adk-install: $AGENT_DIR/agent.py points at '$pkg', which is gone — re-run install" >&2
        status=1
      fi
    fi
    [[ "$status" -eq 0 ]] && echo "adk-install: mount OK ($AGENT_DIR)"
    exit "$status"
    ;;

  uninstall)
    rm -rf "$AGENT_DIR" "$READONLY_DIR"
    rm -f "$PROJECT/.loop-spec/adk-install.json"
    rmdir "$MOUNT_DIR" 2>/dev/null || true
    echo "adk-install: removed the loop-spec ADK mount under $MOUNT_DIR"
    ;;
esac
